### PR TITLE
Fix for github actions

### PR DESCRIPTION
**Pull request by abretaud**
Some little changes to make it work on github actions

### CODE REVIEW

**Comment by bgruening** [comment]
Mh, does this break travis? Should we have for the time being two Makefiles? Travis and GHA?

**Comment by abretaud** [comment]
Good question, I think it's mostly harmless, but who knows, lemme check

**Comment by abretaud** [comment]
Looks like it works both for travis and GA :tada::
https://travis-ci.org/github/abretaud/docker-galaxy-genome-annotation/builds/704638477
https://github.com/abretaud/docker-galaxy-genome-annotation/runs/834277788?check_suite_focus=true
Added a bit of documentation

**Comment by bgruening** [comment]
Mighty!

**Pull request merged**
