### PR TITLE
add six

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@nsoranzo I could find an obvious reason why six is not installed with bioblend, but this seems to be needed since yesterday.

**Comment by jmchilton** [comment]
I'm getting bizarre six problems too - https://travis-ci.org/galaxyproject/planemo/jobs/238174042 - I'm not sure what is up or if it is related.

**Comment by jmchilton** [comment]
Maybe this https://github.com/pypa/setuptools/pull/1043/files - I think setuptools was broken on PyPI for sometime recently.

**Comment by nsoranzo** [comment]
Yes, it's fixed in setuptools 36.0.1, see https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v3601

**Comment by bgruening** [comment]
I just need to be more patient :)

**Pull request merged**
